select * from customer limit 20;

-- what is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

-- which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'yes'
AND purchase_amount >= (
    SELECT AVG(purchase_amount)
    FROM customer
);

-- which are the top 5 products with the highest average review rating?
select item_purchased, Round(AVG(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- compare the average Purchase Amounts between standard and express shipping.
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('standard', 'Express')
group by shipping_type

-- Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers
select subscription_status,
count(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_speed desc;

-- which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
Round(100 * sum(case when discount_applied = 'Yes' Then 1 Else 0 end) /COUNT(*) ,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- segment customers into New, Returning, and loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case
   when previous_purchases = 1 then 'New'
   when previous_purchases between 2 and 10 then 'Returning'
   else 'loyal'
   end as customer_segment
   from customer
   )
   
   select customer_segment, count(*) as "Number of customer"
   from customer_type
   group by customer_segment
   
-- what are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
Row_Number() over(partition by category order by count(customer_id)Desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

-- are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;




